version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - # Install any required dependencies for deployment

  pre_build:
    commands:
      - echo "Downloading compiled binary..."
      - aws s3 cp s3://eka-a-releaser-build-output/eks-a-releaser-build .
      - unzip eks-a-releaser-build
      - cd cli-releaser

  build:
    commands:
      - echo "Deploying Go CLI binary..."
      - ./eks-a-releaser-cli create-branch
      - ./eks-a-releaser-cli update-MakeFile
      - # Run any additional deployment scripts or commands
