---
env:
  variables:
    GITHUB_ACCESS_TOKEN2: "{{ resolve:secretsmanager:GITHUB_ACCESS_TOKEN2:SecretString:GITHUB_ACCESS_TOKEN2 }}"
    ReleaseYAMLSha: "{{ resolve:secretsmanager:ReleaseYAMLSha:SecretString:ReleaseYAMLSha }}"

phases:
  install:
    runtime-versions:
      golang: 1.22.4

  pre-build:
    commands:
      - go mod download

  build:
    commands:
      - go build -o my-cli ./eks-a-releaser/main.go
